/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__CONF_H__)
#define __CONF_H__


/* the default :-separated search path */
#if !defined(DEFAULTCALCPATH)
#define DEFAULTCALCPATH ".;/usr/share/osso_calculator_engine"
#endif /* DEFAULTCALCPATH */

/* the default :-separated startup file list */
#if !defined(DEFAULTCALCRC)
#define DEFAULTCALCRC "/usr/share/osso_calculator_engine/startup:~/.calcrc:./.calcinit"
#endif /* DEFAULTCALCRC */

/* the default pager to use */
#if !defined(DEFAULTCALCPAGER)
#define DEFAULTCALCPAGER "more"
#endif /* DEFAULTCALCPAGER */

/* where the echo command is located */
#if !defined(ECHO_PROG)
#define ECHO_PROG "/bin/echo"
#endif /* ECHO_PROG */


#endif /* !__CONF_H__ */
