/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_USTAT_H__)
#define __HAVE_USTAT_H__


/* do we have or want ustat()? */
#define HAVE_USTAT /* yes */


#endif /* !__HAVE_USTAT_H__ */
