/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_GETSID_H__)
#define __HAVE_GETSID_H__


/* do we have or want getsid()? */
#define HAVE_GETSID /* yes */


#endif /* !__HAVE_GETSID_H__ */
